# If set to false, particles will not spawn
enabled: true

# Here you can find every particle: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
particle: END_ROD

# Interval in ticks (20 ticks = 1 second)
interval: 5

# The radius in which the particles spawn around the player
radius: 20

# The number of particles to spawn
count: 100
